### ISSUE TITLE
Request: quit-event

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#114]
Quests don't use unique timer instances (meaning if you quit and retake it the timer doesn't really reset) - this can lead to inadvertent/undeserved failure for users who quit and retake quests.

A suggestion would be a `quit-event` option so that I can run CancelTimer then, too.

```
  Fishing Challenge:
    name: "Beat the Fishing Newbie's challenge"
    npc-giver-id: 11
    ask-message: "<gray>Fishing Newbie<white>: I've got a fishing challenge for you, do you think you're up to it?"
    finish-message: "<gray>Fishing Newbie<white>: Wow! Nice work!"
    stages:
      ordered:
        '1':
          fish-to-catch: 32
          start-event: 10MinuteTimer
          finish-event: CancelTimer
    redo-delay: 43200
    rewards:
      money: 100
      quest-points: 3
```

```
  10MinuteTimer:
    timer: 600
  CancelTimer:
    cancel-timer: true
```
