### ISSUE TITLE
Items could not be delivered while renamed

### ISSUE THREAD

**Issue by masterstreamer** [FlyingPikachu/Quests#164]
Version: 3.0.0-Naomi

If a stage is to deliver a item and you set an Item, the Item always is in english language. Also if the Client runs another language. I thought "you can set the display name of the Item, so it should work", but it doesnt. It says "the Item <ENGLISH NAME> is not a stage of the quest". If you change the client to english and rename the required Item with the amboss to the name set in the quests editor, it works. Maybe you have to work with Material, not with the itemmeta.getDisplayName.

**Comment by RaulCto** [comment]
Hi good day masterstreamer. I'm latin and i have this plugin on my sever and never have that problem. Same as you, I have custome names and even lores. And all of them works perfect. 
The issue will be to check agian the format that you give them. It has to be the same to deliver.

If you still have the same problem, and if you want to replay go ahead. Nice day.

**Comment by masterstreamer** [comment]
@RaulCto Could you please provide me an example quest? Here is mine, maybe you can find an error:
```
custom1:
    name: Name
    npc-giver-id: 28
    redo-delay: 86400
    ask-message: Hello text
    finish-message: thanks!
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-COBBLESTONE:amount-1:displayname-Teststone
          npc-delivery-ids:
          - 28
          delivery-messages:
          - thanks
    rewards:
      items:
      - name-LEASH:amount-1
      money: 12000
      quest-points: 18
```
So if I click with an cobblestone stands there: "Cobblestone x 1 is not a required item for this quest!"

**Comment by RaulCto** [comment]
@masterstreamer Hi, i just copy and paste that quests example and noticed that you dont have the **gui-display:**
`custom4:
    name: Name
    npc-giver-id: 2
    redo-delay: 86400
    ask-message: Hello text
    finish-message: thanks!
    gui-display: name-WOOD:amount-1
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-COBBLESTONE:amount-1:displayname-Teststone
          npc-delivery-ids:
          - 2
          delivery-messages:
          - thanks
    rewards:
      items:
      - name-LEASH:amount-1
      money: 12000
      quest-points: 18
`
I use the plugin: CustomEnchantments to change the name of my cobbletone and it just work perfect. Here is the picture and the moment that i have just change the name of my cobblestone 
' You have successfully set the item's Name! '
https://imgur.com/a/uHSd1

You can try it to copy and paste my code. Just change the NPC number. 
I will be still here for any questions. Nice day.

**Comment by RaulCto** [comment]
@masterstreamer Hi, i just copy and paste that quests example and noticed that you dont have the gui-display: 

```
custom4:
    name: Name
    npc-giver-id: 2
    redo-delay: 86400
    ask-message: Hello text
    finish-message: thanks!
    gui-display: name-WOOD:amount-1
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-COBBLESTONE:amount-1:displayname-Teststone
          npc-delivery-ids:
          - 2
          delivery-messages:
          - thanks
    rewards:
      items:
      - name-LEASH:amount-1
      money: 12000
      quest-points: 18
```

I use the plugin: CustomEnchantments to change the name of my cobbletone and it just work perfect. Here is the picture and the moment that i have just change the name of my cobblestone
"" You have successfully set the item's Name! ""
https://imgur.com/a/uHSd1

You can try it to copy and paste my code. Just change the NPC number.
I will be still here for any questions. Nice day.
