### ISSUE TITLE
Finish Events Error

### ISSUE THREAD

**Issue by Segysmundo** [FlyingPikachu/Quests#320]
This issue had already been reported almost a year ago but since the person in charge wasn't able to reproduce the problem it was deemed invalid.

I'm not entirely sure what is causing it since I've tried eveything I could to make it work with no success.

[Link here.](https://github.com/FlyingPikachu/Quests/issues/138)

_________ ______________________________________________________

Ok so first of all, finish events do work as long as quests only have 1 stage. This means that if I suddenly add a new stage to that quest the finish event will no longer work.

The only "solution" me and others have found, is moving the **Finish Event of Stage 1** to **Start Event of Stage 2**.

Heres is an example event and 2 quests using it.

**Example Event**
  ```
TestEvent:
    commands:
    - give <player> 1 20
    teleport-location: world 159.0 69.0 147.0
```
When the event activates, the player must be teleported to those coordinates and recieve 20 of item with ID 1.

**Example Quest 1**
```
    name: Test1
    block-start: world 168.0 70.0 146.0
    redo-delay: 1
    ask-message: Start
    finish-message: End
    stages:
      ordered:
        '1':
          break-block-names:
          - SAND
          break-block-amounts:
          - 1
          finish-event: Test
```
When completing this quest the finish event will execute succesfully as there is only 1 stage.

**Example Quest 2**
```
    name: Test2
    block-start: world 168.0 70.0 146.0
    redo-delay: 1
    ask-message: Start
    finish-message: End
    stages:
      ordered:
        '1':
          break-block-names:
          - SAND
          break-block-amounts:
          - 1
          finish-event: Test
        '2':
          break-block-names:
          - Cactus
          break-block-amounts:
          - 1
```
When concluding stage 1, the quest will continue to stage 2 completely ignoring the finish event, the reason for this I haven't figured out yet.

Since no error messages are shown on console it's quite hard to find out what the issue is, it seems weird that for some this exact quest and event would work and for others it wouldn't, makes me think it has to do with some sort of plugin incompatibility.
