### ISSUE TITLE
Block Break Not Updating

### ISSUE THREAD

**Issue by checkplys** [FlyingPikachu/Quests#322]
When I break a block the quest doesn't update

My file:
```
quests:
  custom1:
    name: Minerador
    npc-giver-id: 0
    redo-delay: 86400
    ask-message: Minere 16 packs de cobblestone para mim
    finish-message: §cObrigado, pode pegar denovo com esse dinheiro de bonus
    stages:
      ordered:
        '1':
          break-block-names:
          - COBBLESTONE
          break-block-amounts:
          - 1024
    rewards:
      money: 2000
```
