### ISSUE TITLE
Repeatable planner quests unavailable to players

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#367]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

3.3.0-b300

(__Required__) Please describe the problem and how to replicate it. Any console errors?

After changing redo-delay to the new Planner system, quests are unavailable for players who previously completed them. No errors in the server log. The quest appears under /quests list

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

```yaml
  Daily Wheat:
    name: Wheat for the wanting (Daily)
    planner:
      start: 30:2:2018:19:0:0:SystemV/EST5
      repeat: 86400
    npc-giver-id: 23
    ask-message: <darkgreen>We need 5 stacks of wheat today to feed the people, can
      you help?
    finish-message: <darkgreen>Thank you kindly, your efforts are most appreciated!
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-wheat:amount-320
          npc-delivery-ids:
          - 23
          delivery-messages:
          - Thanks, keep it up!
    rewards:
      money: 50
      quest-points: 1
```
