### ISSUE TITLE
Seeking help configuring planner for desired functionality

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#390]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

3.3.0-b300

(__Required__) Please describe the problem and how to replicate it. Any console errors?

What I'd like to have happen is daily/weekly quests that emulate the functionality in Guild Wars 2. (Like many features on my server that have GW2 principles, I think this is great game design.) Randomization can come later - to start, I have a bunch of quests that currently have a ~12 hour cooldown on completion. Instead, I'd like the availability of them to roll over for every player every day at the same time (or, for weeklies, on Fridays at the same time).

https://wiki.guildwars2.com/wiki/Daily

I tried setting no cooldown and planner availability daily at the specified time, but it let players take multiple copies of the same quest. How should I set the planner options to achieve this? Below is an example current daily quest.

Let me know if I can provide more information - and as mentioned in the other "issue" I filed recently, I'm happy to chat at your leisure. I recently did a screenshare with Staartvin of AutoRank so I could show him some various systems in other games and on my server as part of some suggestions. Thanks for all your hard work, as always!

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

```yaml
  Daily Library:
    name: Navigate the Grand Library (Daily)
    planner:
      start: 30:2:2018:19:0:0:SystemV/EST5
      repeat: 86400
      cooldown: 43200
    npc-giver-id: 182
    ask-message: '<gray>Bookkeeper<white>: Ah, hello, and well done on navigating
      the Library. Go to the Quest Master for your reward.'
    finish-message: '<darkgreen>Quest Master<white>: Excellent work! Here''s your
      prize.'
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 39
    rewards:
      money: 250
      quest-points: 1
```
