### ISSUE TITLE
Items-to-deliver requests ink sacs rather than cocoa

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#402]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

3.3.2-b312

(__Required__) Please describe the problem and how to replicate it. Any console errors?

Prompt asks for ink sacs, despite correctly accepting cocoa: https://imgur.com/a/SJDnUQ3

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
```yaml
  Daily Cocoa:
    name: Cocoa for the countrymen (Daily)
    planner:
      start: 30:2:2018:19:0:0:SystemV/EST5
      repeat: 86400
      cooldown: 43200
    npc-giver-id: 25
    ask-message: <darkgreen>We need 5 stacks of coacoa today to feed the people, can
      you help?
    finish-message: <darkgreen>Thank you kindly, your efforts are most appreciated!
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-ink_sack:amount-320:data-3
          npc-delivery-ids:
          - 25
          delivery-messages:
          - Thanks, keep it up!
    rewards:
      money: 50
      quest-points: 1
```
