### ISSUE TITLE
Player can't deliver redstone to NPC

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#407]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

3.3.2-b312

(__Required__) Please describe the problem and how to replicate it. Any console errors?

Player right clicks NPC with redstone, either gets list of quests or "no more quests available." This issue is inconsistent - it happened for at least one player, but not for all players.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

```yaml
  Unlock Avenfeld:
    name: Discover a new realm
    ask-message: '<darkgreen>Royal Geographer<white>: We''ve made new developments
      in magical transportation, and discovered a new realm, Avenfeld. I''d like you
      to go there. I can teach you the spell, but you''ll need to gather the requisite
      magical items in order to visit.'
    finish-message: '<darkgreen>Royal Geographer<white>: Congratulations - you''ve
      made it to Avenfeld! I''m sure further adventures are afield.'
    npc-giver-id: 33
    requirements:
      quests:
      - Hunt more Elites
      fail-requirement-message: '<darkgreen>Royal Geographer<white>: Sorry, I don''t
        have any quests for you, yet.'
    stages:
      ordered:
        '1':
          start-message: '<darkgreen>Royal Geographer<white>: Bring me the items you
            need for the spell - redstone, ghast tears, ender eyes, and slime balls.'
          items-to-deliver:
          - name-redstone:amount-128
          - name-ghast_tear:amount-16
          - name-eye_of_ender:amount-16
          - name-slime_ball:amount-32
          npc-delivery-ids:
          - 33
          - 33
          - 33
          - 33
          delivery-messages:
          - Thanks, keep it up!
          - Thanks, keep it up!
          - Thanks, keep it up!
          - Thanks, keep it up!
          finish-event: avenfeld-spell-teach
    rewards:
      money: 250
      quest-points: 5
```
