### ISSUE TITLE
Timer not parsing properly

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#417]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4-b316

(__Required__) Please describe the problem and how to replicate it. Any console errors?
https://cdn.discordapp.com/attachments/191040977652285450/453967874030043168/unknown.png

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
```yaml
  Fishing Challenge:
    name: Beat the Fishing Newbie's challenge
    npc-giver-id: 11
    ask-message: '<gray>Fishing Newbie<white>: I''ve got a fishing challenge for you,
      do you think you''re up to it?'
    finish-message: '<gray>Fishing Newbie<white>: Wow! Nice work!'
    stages:
      ordered:
        '1':
          fish-to-catch: 32
          start-event: 10MinuteTimer
          finish-event: CancelTimer
    planner:
      start: 30:2:2018:19:0:0:SystemV/EST5
      repeat: 86400
      cooldown: 43200
    rewards:
      money: 100
      quest-points: 1
```

```yaml
events:
  10MinuteTimer:
    timer: 600
  CancelTimer:
    cancel-timer: true
```
