### ISSUE TITLE
Quests Editor not saving my quests

### ISSUE THREAD

**Issue by ErenBlack** [FlyingPikachu/Quests#45]
- Quests verion 2.9.0, no modules

- The quests editor does not save my quests.

Only warning found in the console: (from bottom up. Using MCPRO so the console prints backwards)
```

14.07 13:57:30 [Server] WARN Could not save data.yml to plugins/Quests/data.yml because data.yml already exists. 
14.07 13:57:30 [Server] WARN Could not save events.yml to plugins/Quests/events.yml because events.yml already exists. 
14.07 13:57:30 [Server] WARN Could not save quests.yml to plugins/Quests/quests.yml because quests.yml already exists. 
14.07 13:57:30 [Server] INFO Enabling Quests v2.9.0-b140
```

```
 quests:
  Miner:
    name: Stone Miner
    ask-message: <yellow>Mine <purple>10<yellow> blocks of <purple>Stone<yellow> and gather the <purple>10 pieces of <purple>Cobblestone<yellow>.
    finish-message: <yellow>Well done. Here is your reward.
    redo-delay: 1800
    requirements:
      items:
      - name-wood_pickaxe:amount-1
      remove-items:
      - false
      fail-requirement-message: <red>You must have a <purple>Wooden Pickaxe<red> first.
    stages:
      ordered:
        '1':
          break-block-names:
          - stone
          break-block-amounts:
          - 10
          break-block-durability:
          - 0
    rewards:
      money: 1000
      quest-points: 1
  Hunter:
    name: Mob Hunter
    ask-message: <yellow>Kill an assortment of Mobs.
    finish-message: <yellow>Excellent. Here is a <purple>Diamond Sword<yellow>.
    requirements:
      quests:
      - Stone Miner
      fail-requirement-message: <red>Complete <purple>Stone Miner<red> first.
    stages:
      ordered:
        '1':
          death-event: DeathFail
          mobs-to-kill:
          - Pig
          mob-amounts:
          - 3
          finish-event: GoodJob
        '2':
          death-event: DeathFail
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 2
          finish-event: GoodJob
        '3':
          death-event: DeathFail
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 1
    rewards:
      items:
      - name-diamond_sword:amount-1
      exp: 100
      quest-points: 1
  CatchFish:
    name: Catch Fish
    ask-message: <yellow>Catch some fish!
    finish-message: <yellow>Good job. Here is some <green>experience<yellow>.
    requirements:
      quests:
      - Stone Miner
      fail-requirement-message: <red>Complete <purple>Stone Miner<red> first.
    stages:
      ordered:
        '1':
          start-event: FishingStart
          death-event: DeathFail
          chat-events:
          - RodEvent
          chat-event-triggers:
          - rod
          fish-to-catch: 5
    rewards:
      exp: 250
```
