### ISSUE TITLE
Dyed firework stars not accepted for quest

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#620]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.0-b595

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

The NPC will only accept a dataless firework star, which is impossible to craft by players.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

```yaml
  Unlock Flamebolt Spell:
    name: Learn the Flamebolt spell
    ask-message: "<darkgreen>Stoic Sage<white>: The Flamebolt spell hurls a bolt of flame ahead of you, damaging the first enemy hit. When you're ready to learn it, bring me what I need so that I can teach you."
    finish-message: "<darkgreen>Stoic Sage<white>: Congratulations, you're ready to learn Flamebolt! Give it a try with \"/cast flamebolt.\""
    npc-giver-id: 192
    requirements:
      quests:
      - Learn the Blink spell
      permissions:
      - magicspells.learn.flamebolt
      fail-requirement-message: "<darkgreen>Stoic Sage<white>: You're not ready for this quest yet!"
    stages:
      ordered:
        '1':
          start-message: "<darkgreen>Stoic Sage<white>: I'll need some items from you in order to teach you the spell. Redstone to channel the magical energy into you, blaze rods to channel fire magic, fire charges to give you the energy to summon flame projectiles, and gold for magical alchemy. After this, you'll need a chunk of crystallized experience from the Arch Artificer."
          items-to-deliver:
          - name-redstone:amount-128
          - name-blaze_rod:amount-128
          - name-firework_charge:amount-128
          - name-gold_ingot:amount-64
          npc-delivery-ids:
          - 192
          - 192
          - 192
          - 192
          delivery-messages:
          - Thanks, keep it up!
          - Thanks, keep it up!
          - Thanks, keep it up!
          - Thanks, keep it up!
        '2':
          start-message: "<darkgreen>Stoic Sage<white>: Now, bring me a chunk of crystallized experience from the Arch Artificer."
          custom-objectives:
            custom1:
              name: MythicItem NPC Deliver Objective
              count: -999
              data:
                NPC IDs: '192'
                Objective Name: Deliver a chunk of crystallized experience to the Stoic Sage
                Lore: fair number of levels.
                HoldItem: 'true'
                Amount: '1'
                Material: EMERALD
                NameEnds: NONE
                TimeLimit: '-1'
                MythicItem: NONE
                RemoveItem: 'true'
                TargetConditions: NONE
                Conditions: NONE
          complete-message: "<darkgreen>Stoic Sage<white>: Excellent, now I can teach you the spell!"
          finish-event: flamebolt-spell-teach
    rewards:
      money: 100
      quest-points: 3
```
