### ISSUE TITLE
Multiple Stages using the same Custom Objective do not have their own data map

### ISSUE THREAD

**Issue by frost-byte** [FlyingPikachu/Quests#625]
**What is your Quests version / build number (do _not_ say "latest")?**
3.4.9

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I have created CustomObjectives, which are contained in my plugin, which registers them with Quests, instead of using a module.   

Whenever I use the same CustomObjective for multiple stages, with different values assigned to the datamap, the values are overwritten by whatever was specified for the last stage to use that CustomObjective.

If I manually edit the quests.yml and change the values for each stage using that CustomObjective, then they all work properly, but I'm not sure why each stage does not have it's own unique entries for the CustomObjective.  (Looking over your code, it seems that you append a prefix with the stage number in front of the key in the datamap)

You can try to reproduce this by using one of your own custom objectives in multiple stages of a quest.

**Comment by frost-byte** [comment]
Alright, that's fine, I've converted to using a module and the actual bug I was reporting here still exists.

> Whenever I use the same CustomObjective for multiple stages, with different values assigned to the
> datamap, the values are overwritten by whatever was specified for the last stage to use that
> CustomObjective.

Here is an excerpt from my quests.yml, you can see that the values for the second stage weren't entered:
```yaml
  custom6:
    name: Questes 123
    ask-message: Questes, Questes, 1 2 3..?
    finish-message: That's a lot of Questes
    gui-display: name-GRASS_PATH:amount-1
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Interaction Objective
              count: 1
              data: &id001
                Task: Create a Shop Sign
                Interaction: CreateShopSign
          complete-message: You bought an item
        '2':
          custom-objectives:
            custom1:
              name: Interaction Objective
              count: 1
              data: *id001
    rewards:
      items:
      - name-IRON_NUGGET:amount-29:enchantment-DURABILITY 1:displayname-§rIron Coins:lore-§r§6Currency:meta-type-UNSPECIFIC:enchants-{DURABILITY=1}:ItemFlags-[HIDE_ENCHANTS]
      exp: 500
```
This is what I expected to see:
```yaml
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Interaction Objective
              count: 1
              data: &id001
                Task: Create a Shop Sign
                Interaction: CreateShopSign
          complete-message: You created a shop sign!
        '2':
          custom-objectives:
            custom1:
              name: Interaction Objective
              count: 1
              data: *id001
                Task: Buy an item from a Shop
                Interaction: BuyShopItem
```
Not sure about the &id001 and *id001, is that valid yaml?

**Comment by FlyingPikachu** [comment]
Yes, that's actually valid YAML - https://en.wikipedia.org/wiki/YAML#Advanced_components

I wasn't able to replicate this with a quick test module. Would you mind sharing your code? If you intend to release it as premium, feel free to leave your spigotmc.org username and I'll just contact you there instead.

**Comment by frost-byte** [comment]
I'm wondering if the issue might be caused by the following in the CustomObjective class.

```Java
public final Map<String, Object> datamap = new HashMap<String, Object>();
```
The final keyword would prevent the address of the map from changing, would it not?
In several of your Prompt classes you take the value of the found CustomObjective and use it's datamap.

For example, in the CustomObjectivesPrompt in the acceptInput method:
```Java
@Override
public Prompt acceptInput(ConversationContext context, String input) {
	if (input.equalsIgnoreCase(Lang.get("cmdCancel")) == false && input.equalsIgnoreCase(Lang.get("cmdClear")) == false) {
		CustomObjective found = null;
		for (CustomObjective co : plugin.getCustomObjectives()) {
			if (co.getName().equalsIgnoreCase(input)) {
				found = co;
				break;
			}
		}
		if (found == null) {
			for (CustomObjective co : plugin.getCustomObjectives()) {
				if (co.getName().toLowerCase().contains(input.toLowerCase())) {
					found = co;
					break;
				}
			}
		}
		if (found != null) {
			if (context.getSessionData(pref + CK.S_CUSTOM_OBJECTIVES) != null) {
				LinkedList<String> list = (LinkedList<String>) context.getSessionData(pref + CK.S_CUSTOM_OBJECTIVES);
				LinkedList<Map<String, Object>> datamapList = (LinkedList<Map<String, Object>>) context.getSessionData(pref + CK.S_CUSTOM_OBJECTIVES_DATA);
				LinkedList<Integer> countList = (LinkedList<Integer>) context.getSessionData(pref + CK.S_CUSTOM_OBJECTIVES_COUNT);
				if (list.contains(found.getName()) == false) {
					list.add(found.getName());
                                        // HERE         \/\/\/\/\/\/
					datamapList.add(found.datamap);
					countList.add(-999);
					context.setSessionData(pref + CK.S_CUSTOM_OBJECTIVES, list);
					context.setSessionData(pref + CK.S_CUSTOM_OBJECTIVES_DATA, datamapList);
				} else {
					context.getForWhom().sendRawMessage(ChatColor.YELLOW + Lang.get("stageEditorCustomAlreadyAdded"));
					return new CustomObjectivesPrompt();
				}
			} else {
				LinkedList<Map<String, Object>> datamapList = new LinkedList<Map<String, Object>>();
				LinkedList<Integer> countList = new LinkedList<Integer>();
                                // HERE         \/\/\/\/\/\/
				datamapList.add(found.datamap);
				countList.add(-999);
				LinkedList<String> list = new LinkedList<String>();
				list.add(found.getName());
				context.setSessionData(pref + CK.S_CUSTOM_OBJECTIVES, list);
				context.setSessionData(pref + CK.S_CUSTOM_OBJECTIVES_DATA, datamapList);
				context.setSessionData(pref + CK.S_CUSTOM_OBJECTIVES_COUNT, countList);
			}
			// Send user to the count prompt / custom data prompt if there is any needed
			if (found.isEnableCount()) {
				return new CustomObjectiveCountPrompt();
			}
			if (found.datamap.isEmpty() == false) {
				context.setSessionData(pref + CK.S_CUSTOM_OBJECTIVES_DATA_DESCRIPTIONS, found.descriptions);
				return new ObjectiveCustomDataListPrompt();
			}
			//
		} else {
			context.getForWhom().sendRawMessage(ChatColor.YELLOW + Lang.get("stageEditorModuleNotFound"));
			return new CustomObjectivesPrompt();
		}
	} else if (input.equalsIgnoreCase(Lang.get("cmdClear"))) {
		context.setSessionData(pref + CK.S_CUSTOM_OBJECTIVES, null);
		context.setSessionData(pref + CK.S_CUSTOM_OBJECTIVES_DATA, null);
		context.setSessionData(pref + CK.S_CUSTOM_OBJECTIVES_DATA_TEMP, null);
		context.getForWhom().sendRawMessage(ChatColor.YELLOW + Lang.get("stageEditorCustomCleared"));
	}
	return new CreateStagePrompt(plugin, stageNum, questFactory, citizens);
}
```

**Comment by frost-byte** [comment]
Alright, I've tested this out and I believe that was the problem.
I circumvented the issue by adding a method to the CustomObjective class:

```Java
	public Map<String, Object> copyDataMap() {
		Map<String, Object> newMap = new HashMap<>();
		if (datamap != null && !datamap.isEmpty())
		{
			for (String key : datamap.keySet())
				newMap.put(key, null);
			return newMap;
		}
		return null;
	}
```
Now, instead of doing 
```Java
datamapList.add(found.datamap);
```
I do
```Java
datamapList.add(found.copyDataMap());
```
I no longer have the issue when I do this.

**Comment by frost-byte** [comment]
Also, I understand your point about the advanced feature of yaml.  Unfortunately, in my case, the only thing the the two stages had in common was the name and count, not the data values.  

In addition, I had already defined the first stage to have an Interaction Objective using a BuyShopItem, when I then created the Interaction Objective for the second stage - the CreateShopSign Interaction - that overwrote the first stage and then just referenced it for the second, when obviously that's not what I was going for.

**Comment by frost-byte** [comment]
I understand about taking over for a project, I've come across many plugins in which that's happened. So I'm not pointing fingers or anything, it can be a lot of work to try to make heads or tails of anything like this, especially if you have a lot of people extending or expecting it to work in a certain way.

Without modifying the access privileges for datamap, you could try the suggestion I made.  Simply create a method to provide a copy of the datamap.  The intention really isn't to modify the keys that have been added, but to allow for different data for what would normally be instances of the same objective.

As I see it, the code isn't really instantiating more than one copy of each CustomObjective, but more or less using it in a template fashion.  The whole point of using the final keyword has to do with the fact that it was specified as public, and also to maintain what the keys or composition of the Objective.

Everything that's persisted to each stage is stored as part of a configuration, while it's being input, it's just added to maps for the current quest, using keys starting with the stage + number prefix. From what I can tell, the information that is pulled from each CustomObjective class are the keys and the descriptions? 

If by changing the code to use the method I suggested would break compatibility, then one option is to add a flag to the configuration that users can set.  If true then the method I suggested could be used, otherwise, by default it would be false and continue to use what's already in place.

One idea might be to have CustomObjectiveData class, basically a glorified wrapper for the datamap. However I don't know how would affect everything, but it seems like there should be a separation between what each CustomObjective defines as the 'blueprint' versus what would normally be the state or data stored an instance.

**Comment by FlyingPikachu** [comment]
First I should say I wrongly assumed that CustomObjective.getDatamap() did what your copyDataMap() does based purely on the name, but it has an entirely different purpose. Go figure.

Your way obviously works, but the fact remains that Quests is at fault here. I've just created a new [api-update](https://github.com/FlyingPikachu/Quests/tree/api-update) branch that I'd like you to check out. Essentially what I've done it set the data map private, added getter methods, and deprecated a few of the older ones for clarity. The new `addDatum(name, object)` method should cover what you're trying to do, but let me know whether it's sufficient.

**Comment by FlyingPikachu** [comment]
I've gone and merged, deleting the branch. You can view the changes here:
https://github.com/FlyingPikachu/Quests/commit/cff144479be2a07e2641b7f661b802ddf1fb7795

Feel free to comment with suggestions in order to re-open.

**Comment by frost-byte** [comment]
I just tried with your latest build v3.6.0-b611, unfortunately the issue I had before still remains.
When you load each CustomObjective from their respective modules, you only instantiate one object of each class?  Even using the new getData method, any request will always retrieve the same HashMap.  The copyDataMap() method I created takes this into consideration, so that if I want to define multiple stages using the same type of CustomObjective, the same keys will be used, but not the same data.

So using the latest version does not address that.  The quests.yml still shows that it's just readdressing the last set of data entered and not using unique information for two Stages using the same Custom Objective.

```yaml
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Interaction Objective
              count: 1
              data: &id001 <--- I should not be seeing this, each stage has different values defined
                Task: Create a shop chest <-- This should have been saved to stage 2, instead what was
                Interaction: CreateShopSign <-- originally entered was overwritten and then referenced
          complete-message: item bought
        '2':
          custom-objectives:
            custom1:
              name: Interaction Objective
              count: 1
              data: *id001 <-- Again, I do not want to reference the same data - they are different
          complete-message: Chest created
```

**Comment by FlyingPikachu** [comment]
So my understanding is the `copyDataMap` method you've made creates a new map based on the actual map in Quests, then clears all of the new map's values. With the recent changes, it should now be made to look something like this:

```
// untested code
public Map<String, Object> copyDataMap() {
	Map<String, Object> newMap = new HashMap<>();
	if (getData() != null && !getData().isEmpty())
	{
		for (String key : getData().keySet())
			newMap.put(key, null);
		return newMap;
	}
	return null;
}
```

Either way, you're ending up with a copy of the map; not the actual map itself.  Rather than use the workaround in your other block of code, you can now use `addDatum("Title", datum)` to add to the actual internal map now that it isn't final. Note that I'm hesitant to make a `setData` method here due to the high possibility of user error (not you personally, but I digress). As long as you use a different datum value each time (or a different key), the plugin shouldn't resort to using YAML anchors.

Also, I'd like to note that the maker of the MythicMobs module just updated based on the recent API changes (see #644) and although it seems to me that he's erroneously trying to update a local copy of the map, it may be worth a look - https://github.com/BerndiVader/MythicMobsQuestsModule/commit/4a3c951e59fd0ed1abbe76fae6e212cb189e5af9

**Comment by FlyingPikachu** [comment]
So it seems our understandings of the API differ, which isn't surprising since again I didn't write it and the guide you went off of was ancient and poorly-worded.

With `copyDataMap()`, the Object values that you're resetting to null contain the default data for your custom objective, which is null until it receives prompt input from the player creating a quest. I added the `addDatum(name, object)` because it was my impression that you wanted to set the default values to something other than null, [like the MythicMobsQuestsModule did](https://github.com/BerndiVader/MythicMobsQuestsModule/blob/a346d24545e874587c0895b30b369492978f6f81/src/com/gmail/berndivader/mythicmobsquests/MythicItemDeliverObjective.java#L122), which should differentiate the config data enough to prevent anchors.

However, your PR #645 does the opposite, setting the values internally to null regardless of what a module specifies. In other words, it would break the MythicMobsQuestsModule if I merged that pull request. The puzzling bit for me is how you're getting the desired results if the the default values are identical (albeit both null). As far as I can tell, that shouldn't be any improvement.

Back to the API doc being ancient - I've gone and updated the entire page, including all examples. You'll notice I've changed the methods again for easy of use and readability. Rather than adding a name, description, and default value separately, I've condensed it into the following:

```java
                               // (Name,     Description,     Default value)
        this.addStringPrompt("Item name", "Enter number of blocks:", "DIRT");
```

Furthermore, I've implemented the changes in your example code from earlier, which now looks like:

```java
package com.ve.mc.vanillaquests;

import com.ve.mc.interactions.Interaction;
import com.ve.mc.interactions.InteractionEvent;
import com.ve.mc.utility.PluginUtil;
import me.blackvein.quests.CustomObjective;
import me.blackvein.quests.Quest;
import me.blackvein.quests.Quester;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import java.util.Map;

public class InteractionObjective extends CustomObjective {
    // Get the Quests plugin
    Quests qp = (Quests)Bukkit.getServer().getPluginManager().getPlugin("Quests");

    // Construct the objective
    public InteractionObjective() {
        this.setName("Interaction Objective");
        this.setAuthor("Jane Doe");
        this.setShowCount(true);
        this.setCountPrompt("Enter the amount that the player must drop:");
        this.addStringPrompt("Interaction", "Enter the number of times the player needs to complete the interaction:", "5");
        this.addStringPrompt("Task", "Enter the message displayed in the quest log.", "Default_msg");
        this.setDisplay("%Task%");
    }

    // Catch the player event
    @EventHandler
    public void onInteraction(InteractionEvent event) {
	Interaction interaction = event.getInteraction();
	Player player = event.getPlayer();
	Quester quester = qp.getQuester(event.getPlayer().getUniqueId());

	if (quester == null || quester.getCurrentQuests().isEmpty()) return;

	for (Quest q : quester.getCurrentQuests().keySet()) {
		Map<String, Object> map = getDataForPlayer(player, this, q);
		if (map == null) continue;

		String i = (String)map.get("Interaction");
		if (i == null || i.isEmpty()) continue;

		Interaction required = Interaction.findByName(i);
		if (required == null || !required.equals(interaction)) continue;
			
		incrementObjective(player, this, 1, q);
	}
    }
}
```

Obviously, I can't test it without your Interaction code, but it should be clear I didn't change much. However, I'd like to question a few things that I didn't pick up on earlier:

* You have setShowCount() enabled, which sort of overrides other prompts asking for a number (the "Interaction" prompt). Shouldn't that be disabled?
* I believe setDisplay() is intended to dictate how the objective will appear in the quest log. So isn't the "Task" prompt unnecessary? Then just do something like setDisplay("Interactions needed: %count%)"

Now none of that's not to say your way shouldn't work, as I'm also open to making changes to ease both of our confusion, but I'm still confident the plugin was behaving as expected (or at least, how I expected it), even if it's ~~not a great~~ terrible system of storing the data (but, I do want to maintain some semblance of backwards-compatibility). I really appreciate your patience in trying to improve on this. Please let me know how you find the code changes.

**Comment by frost-byte** [comment]
I’m still not certain if you are able to see what I was trying to address.

If you were to create multiple stages, using the same CustomObjective, would you be able to set different values for each?

Without my modification, no matter what I enter, only the last values are applied to all instances when I save the quest.  I found this puzzling considering that the data entered is then set into another map, using a key that uniquely identifies it as belonging to that stage.

Unfortunately what is happening is that the CreateStagePrompt references the same memory location for the map, and somehow the values I entered for the first InteractionEvent are being overwritten by what I entered by the second

To address the issue caused for MythicMobs, I could copy the entire datamap. I was specifically just doing that to create a new object, that has it’s own memory address

What I’m trying to accomplish is a simplification of how the api works.  Instead of creating 8-10 different CustomObjective classes that process nearly identical events, in exactly the same way, I can just use one, where the data provided to the objective via the prompt defines what kind it is.

I think everything is fine with the plugin and it works great.  I just perceive, that in this case, the Api isn’t following the DRY principle, and I have to create a lot of duplicate code. I’m basically trying to get around that using metadata.

I also appreciate your patience with all of this as well, I hope this adds some clarification. Again, the easiest way to see the issue is to try to use the same objective in two stages, while entering different values at the Prompt.

**Comment by frost-byte** [comment]
Well, it seems as though I can enter the data for two separate stages using the same CustomObjective with different data.  However, I'm experiencing the issue with them not loading.  The display messages don't show up in the quests journal and stages aren't responding to the events listened for in the CustomObjectives.

**Comment by frost-byte** [comment]
Well, I decided to rebuild and try again, now it appears to be loading. However, I'm now seeing a different issue. Instead of seeing one display message in the quest journal for an objective, I'm seeing one message for each string prompt that I added for the CustomObjective.

Here's a snippet of the constructor for one of my objectives:
```Java
	public ShopkeeperTradeObjective()
	{
		setName("Shopkeeper Trade Objective");
		setAuthor("beerye3");
		setShowCount(true);
		setCountPrompt("Enter the quantity of the item that the player must trade for");
		addStringPrompt("NPC ID", "Enter the ID for the ShopKeeper NPC whose shop the player must browse", null);
		addStringPrompt("npc_name", "Enter the name of that NPC", null);
		addStringPrompt("Item Name", "Enter the Quest Item name", null);
		setDisplay("Acquire %count% %Item Name%(s) from %npc_name%.");
	}
```

here's the data for a stage, taken from the quests.yml:
```yaml
        '2':
          custom-objectives:
            custom1:
              name: Shopkeeper Trade Objective
              count: 1
              data:
                npc_name: Wesson
                Item Name: WeedWhacker
                NPC ID: '62'
          start-event: GiveIronCoin
          start-message: Curry would like you to buy him a Weed Whacker from Wesson
          complete-message: Great! Now return the Weed Whacker to Curry
```
![image](https://user-images.githubusercontent.com/852776/51525610-b3fb4b80-1dfe-11e9-9aea-8cab245e9472.png)
