### ISSUE TITLE
Translation key strings appearing to players

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#664]
https://imgur.com/a/i4kSQVU

**What is your Quests version / build number (do _not_ say "latest")?**

3.6.0-b595

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Take a quest with various items. No errors.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/1gvuXnLK

**Comment by SXRWahrheit** [comment]
1. This server is running CraftBukkit version git-Spigot-2086bb0-2f3ed3b (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

2. Yes:

```yaml
# See https://github.com/FlyingPikachu/Quests/wiki/Configuration
accept-timeout: 60
allow-command-questing: false
allow-command-quests-with-npcs: false
allow-quitting: true
ask-confirmation: true
generate-files-on-join: true
ignore-locked-quests: true
kill-delay: 600
language: en
max-quests: 0
npc-effects:
  enabled: true
  new-quest: note
  redo-quest: note
show-requirements: true
show-titles: false
translate-items: true
translate-subcommands: false
use-compass: true
convert-data-on-startup: false
quester-blacklist:
- UUID
- UUID
- UUID
debug-mode: true
show-npc-effects: true
npc-effect: note
```
3. English (US)
