### ISSUE TITLE
Bug with leather armor

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#675]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests version 3.6.2-b643

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Leather armor quest renders an error to players

https://cdn.discordapp.com/attachments/191040977652285450/541669387539709954/unknown.png

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

```yaml
  Mooving on up:
    name: MOOving on up
    npc-giver-id: 39
    ask-message: "<darkgreen>Quest Master<white>: I reckon you'll want to start heading down deeper to mine some iron. But those caves can be dangerous! Why don't you make some armor? Hunt some cows, use their hides to craft a set of leather armor, and then bring it to me. You know what happens then, right? You guessed it - I'll enchant it!"
    finish-message: "<darkgreen>Quest Master<white>: Hey, that's the stuff. Here's your armor back, with a little touch of magic to boot!"
    requirements:
      quests:
      - Breaking ground
      fail-requirement-message: "<darkgreen>Quest Master<white>: Why don't you go out and do some mining first?"
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-leather_helmet:amount-1
          - name-leather_chestplate:amount-1
          - name-leather_leggings:amount-1
          - name-leather_boots:amount-1
          npc-delivery-ids:
          - 39
          - 39
          - 39
          - 39
          delivery-messages:
          - "<darkgreen>Quest Master<white>: Thanks, keep it up!"
          - "<darkgreen>Quest Master<white>: Thanks, keep it up!"
          - "<darkgreen>Quest Master<white>: Thanks, keep it up!"
          - "<darkgreen>Quest Master<white>: Thanks, keep it up!"
    rewards:
      money: 50
      items:
      - name-leather_helmet:amount-1:enchantment-Unbreaking 1
      - name-leather_chestplate:amount-1:enchantment-Unbreaking 1
      - name-leather_leggings:amount-1:enchantment-Unbreaking 1
      - name-leather_boots:amount-1:enchantment-Unbreaking 1
```

643 has also produced an error on reload that I can't seem to trace:

[Sun, 3. Feb 2019 11:33:23 CST ERROR] Quests was unable to read item argument: amount
[Sun, 3. Feb 2019 11:33:23 CST ERROR] Quests was unable to read item argument: amount

For security, this paste will expire in a week

https://pastebin.com/DkZ8kBfT
