### ISSUE TITLE
More translation key issues

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#695]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.3-b657

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

https://prnt.sc/mkp8gp

A translation key appears, and also only one mob is listed.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

Full file available upon request:

```yaml

  First Mob Hunting:
    name: Cutting your teeth
    npc-giver-id: 190
    ask-message: '§2Warmaster Reinwald§f: It''s time for you to head out into the
      world. I''ve got a lot of work for you to do, but first, I have to make sure
      you''re ready for it. Start by killing a §aZombie§f, §aSkeleton§f, §aSpider§f,
      and §aCreeper§f to show me you know what you''re doing. Be careful, and if you
      see any Veteran or Elite monsters, I suggest you run. You''ll know them when
      you see them.'
    finish-message: '§2Warmaster Reinwald§f: Great work. I have more for you to do,
      when you''re ready.'
    requirements:
      quests:
      - Meet Warmaster Reinwald
      fail-requirement-message: '§2Warmaster Reinwald§f: You''re not quite ready for
        that yet.'
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Zombie
          - Skeleton
          - Spider
          - Creeper
          mob-amounts:
          - 1
          - 1
          - 1
          - 1
    rewards:
      items:
      - name-DIAMOND:amount-1
      - name-IRON_INGOT:amount-6
      money: 100
      quest-points: 3
```
