### ISSUE TITLE
QuestFail Timer not counting down.

### ISSUE THREAD

**Issue by DragaoNimhe** [FlyingPikachu/Quests#705]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.3-b655

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Create a fail event, then assign it as the initial (or any) event on a quest.

My issue is related to this ticket:
https://github.com/FlyingPikachu/Quests/issues/417

I was able to fix the formatting issues, example here:
https://puu.sh/CQlky/9651360726.png

However, as you can see in that screenshot, it's not displaying the actual value of the time. Here are the relevant lines in the language file. I copied the fix you suggested in the ticket above exactly:
timerMessage: "%green%You have%red% seconds%green% to finish this quest"
timerStart: "%green%You have%red% seconds%green% to finish this quest"

I also tried %s and %s%, they both sent as plaintext:
https://puu.sh/CQm3N/73331c4d05.png

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/RZFhgqWe

**Comment by FlyingPikachu** [comment]
I'm guessing you manually edited the quests.yml fail, because there a couple problems with the way it's set up. `event: 1MinFail` is invalid and should probably be `start-event: 1MinFail`. Also, it's on the wrong spot and should be within the stages block, like so:

```yaml
    name: testfail
    npc-giver-id: 137
    ask-message: testask
    finish-message: testfinish
    stages:
      ordered:
        '1':
          break-block-names:
          - Stone
          break-block-amounts:
          - 10
          break-block-durability:
          - 0
          start-event: 11MinFail
```

Support will not be provided for manually edited quests. If you seek further assistance, use the built-in editor and post your findings _in a new issue_, or seek community support from the official Discord.

Lastly, I can't speak for the proper formatting at the time of that ticket you referenced, but the current default string for English is:

`%green%You have%red% <time> seconds%green% to finish this quest/stage`

Note the `<time>` tag which is what indicates the number of seconds.
