### ISSUE TITLE
Repeat option not working

### ISSUE THREAD

**Issue by Ainashi** [FlyingPikachu/Quests#713]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.3-b668

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

I tried to do Daily quests with timer resetting for all players in same time. I was manipulating with start, end and repeat option but with no effect. I don't have any errors in console.
Cooldown is working fine in other quests but it's not what I really wanted.
If I set start date and repeat timer, when I finish quest I can't take it again because of finished state.

Also I tried different examples from others like here: https://github.com/FlyingPikachu/Quests/issues/390 or from Discord. None of them was working for me.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

It's a version for quicker tests in which I wanted reset after 1 minute timer.
https://pastebin.com/Prm7Dd3G

**Comment by FlyingPikachu** [comment]
Your start date is set in the future, so the repeat won't take effect until that time. Set the start date to a past or current date/time to resolve the issue.

**Comment by Ainashi** [comment]
I changed date to: 25:1:2017:0:22:0:Etc/UTC (I tried many different dates and times) and problem still exists. I can take quest once and after it's finished I can't take it again as it's completed and can't be repeated.

**Comment by FlyingPikachu** [comment]
Thinking you may also need to set an end date, but I'll reopen this until I have the opportunity to test it.

**Comment by Ainashi** [comment]
I've tried with end date too. With it if I'm trying to take a quest it's saying all the time that I have to wait even if I'm trying just a second after it should be available so I can't take this quest at all.
Also it says 2 minutes instead of 60 seconds which I have in "repeat".
![obraz](https://user-images.githubusercontent.com/32204470/53370313-b5fc8100-394d-11e9-9931-6c861ed8304f.png)

Exmaple quest: https://pastebin.com/0q7avjm0

**Comment by SXRWahrheit** [comment]
I can confirm that this is happening for me as well. Users have reported being unable to repeat quests.

I used the format we discussed on Discord:

```yaml
  Daily Pumpkins:
    name: Pumpkins for the proles (Daily)
    planner:
      start: 30:2:2018:19:0:0:SystemV/EST5
      repeat: 86400
    npc-giver-id: 24
    ask-message: <darkgreen>We need 5 stacks of pumpkins today to feed the people,
      can you help?
    finish-message: <darkgreen>Thank you kindly, your efforts are most appreciated!
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-pumpkin:amount-320
          npc-delivery-ids:
          - 24
          delivery-messages:
          - Thanks, keep it up!
    rewards:
      money: 50
      quest-points: 1
```

I'll see if I can get on tonight and test it personally to produce an output screenshot, we'll see how I'm doing after the pub.

**Comment by FlyingPikachu** [comment]
Use http://ci.ac3-servers.eu/job/Quests/697/ once available to resolve the issue.

Please note that using the editor now _requires_ you set a start and end date before setting a repeat option. If you've previously set a repeat without a start/end, you'll need to go back in and set a start/end.

Also note that the repeat option is based on the start date, so if you set a repeat for 24 hours and your quest starts at 3:00pm, it'll be available the next day at 3:00pm as well.

**Comment by SXRWahrheit** [comment]
For clarity - does this require a start *and* end? I suppose I could just set the end date to 2999 or something, but this feels like a dirty workaround and might not be intuitive for users who want to have indefinitely-repeatable quests.

The repeat matching the start time is perfect and should be the expected behavior, thank you!

**Comment by FlyingPikachu** [comment]
Yes, because the end is used to calculate the duration of the quest (so when it becomes available again, the plugin knows how long to keep it active for). I hadn't considered what might happen if someone were to set a start-to-end time longer than the repeat time, but you're welcome to try it and see what happens!

**Comment by SXRWahrheit** [comment]
Sorry, is the end time supposed to be 24 hours from the start time, with a 24-hour repeat, if we'd like the quest to repeat every 24 hours? I'm just trying to set up daily repeating quests.

**Comment by FlyingPikachu** [comment]
24 hours was an example, but yes that's what you'd do if you want a daily quest. That said, the repeat operates in seconds, so for 24 hours you'd use a value of 86400 seconds.

**Comment by SXRWahrheit** [comment]
Right, was just writing for simplicity. So to recap:

Start date X
End date X+24h
Cooldown 86400

This together ought to set a quest to be repeatable every 24h, yeah?

**Comment by FlyingPikachu** [comment]
Well no, you don't need to add anything to the end date. Just set the repeat option for 24 hours.

Let's say you want your quest to be available for an hour each day, starting at 3:00pm. It'd look like:

Start 3:00pm
End 4:00pm
Repeat 24h / 86400s

The cooldown is if you want a player to be unable to take the quest again for a certain amount of time. So if you want individual players to only be able to complete the quest once a week, you could set it to 604800s.

**Comment by FlyingPikachu** [comment]
Resolved on Discord. Anyone else reading should direct their question there as well:
https://discordapp.com/invite/d56CQ6e

**Comment by SXRWahrheit** [comment]
For anyone checking this issue later, a quest that can be taken once per day, each day, should use a format like this:

```yaml
  Daily Fishing:
    name: Demonstrate your fishing skills (Daily)
    planner:
      start: 30:2:2018:19:0:0:SystemV/EST5
      end: 30:3:2018:19:0:0:SystemV/EST5
      repeat: 86400
```
