### ISSUE TITLE
Don't display completed-but-repeatable quests as "Completed"

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#92]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
b169

(__Required__) Please describe the problem and how to replicate it. Any console errors?
We've had a previous discussion about this. Currently, a completed repeatable quest will result in no particle effects above NPCs and a listing as "Completed" on the NPC's quest display, with no indication that the quest is repeatable.

Desired behavior is a configuration option (in main plugin config or individual quest options) to display the quest as-if-new or otherwise indicate that it is repeatable both in chat options and with particle effects so that players do not inadvertently miss out on available repeatable quests.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
```yaml
  Daily Fishing:
    name: Demonstrate your fishing skills (Daily)
    redo-delay: 43200
    npc-giver-id: 11
    requirements:
      quests:
      - Teach the newbie to fish
      fail-requirement-message: '<gray>Fishing Newbie<white>: You need to teach me
        how to fish first!'
    ask-message: '<gray>Fishing Newbie<white>: Could you show me a little more of
      your fishing skills?'
    finish-message: '<gray>Fishing Newbie<white>: Awesome! Maybe someday I''ll be
      as good as you are!'
    stages:
      ordered:
        '1':
          fish-to-catch: 16
    rewards:
      money: 50
      quest-points: 1
```
