### ISSUE TITLE
Completed quest A, but the quest B (that has 1 req: complete quest A, can not be taken).

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#94]
Quest 3.0.0
Spigot 1.12

I complete the quest "Knight's Training (Beginner)" and it properly gives me the rewards.
Then I try to take the next quest "Knight's Training (Apprentice)" but it tells me I can't take it yet, even though I completed the only quest required.

Ok I have found why it does this, but maybe add a clause to check for capitals because it usually says "... is not a quest name!" when the quest name is incorrect, maybe also show this message when the capitalization is off, because apparently it accepts incorrectly written names.

No errors are shown.

2 Quests: https://pastebin.com/y58etyC4

**Comment by SXRWahrheit** [comment]
Proper format is like this:

```yaml
  First Fishing:
    name: Teach the newbie to fish
    npc-giver-id: 11
    ask-message: '<gray>Fishing Newbie<white>: I''m trying to learn how to fish....
      if you can teach me, I''ll give you this extra leather armor I have.'
    finish-message: '<gray>Fishing Newbie<white>: Thanks so much, here''s that armor
      I promised!'
    stages:
      ordered:
        '1':
          fish-to-catch: 16
    rewards:
      money: 50
      quest-points: 1
      items:
      - name-leather_boots:amount-1
      - name-leather_chestplate:amount-1
      - name-leather_helmet:amount-1
      - name-leather_leggings:amount-1
  Daily Fishing:
    name: Demonstrate your fishing skills (Daily)
    redo-delay: 43200
    npc-giver-id: 11
    requirements:
      quests:
      - Teach the newbie to fish
      fail-requirement-message: '<gray>Fishing Newbie<white>: You need to teach me
        how to fish first!'
    ask-message: '<gray>Fishing Newbie<white>: Could you show me a little more of
      your fishing skills?'
    finish-message: '<gray>Fishing Newbie<white>: Awesome! Maybe someday I''ll be
      as good as you are!'
    stages:
      ordered:
        '1':
          fish-to-catch: 16
    rewards:
      money: 50
      quest-points: 1
```

Pretty sure it requires matching case, and you have a mismatched b/B.
